### ISSUE TITLE
could not broadcast input array (aka empty MS scan in mzXML file)

### ISSUE THREAD

**Issue by jamesETsmith** [jamesETsmith/msanalysis#7]
### Problem Description

```bash
Traceback (most recent call last):
  File "/Users/ann.lii.rosales/Desktop/Python/msanalysis/examples/05_relative_abundance.py", line 41, in <module>
    data = read_mzXML(mzXML_file)
  File "/Users/ann.lii.rosales/Desktop/Python/msanalysis/msanalysis/data_extraction/utils.py", line 125, in read_mzXML
    intensities[i] = s.get_peaks()[1]
ValueError: could not broadcast input array from shape (0) into shape (26947)
```

---
### Steps to Reproduce
I modified example 5 to plot data from the real `mzXML` file (which we now know is corrupted/problematic) and ran the example:

`bash
python 05_relative_abundance.py
`

---
### Expected/Desired Behaviour
The corrupted mzXML files is beyond our control, but we need a more descriptive error message when this happens in the future.

**Comment by jamesETsmith** [comment]
I fixed this in commit f74aa5d. Here's an example of what the new output looks like:

```bash
(msanalysis) examples$ python 05_relative_abundance.py 
Time to load mzXML file 5.60499906539917
Scan 6080 (0-based indexing) is empty.
Traceback (most recent call last):
  File "05_relative_abundance.py", line 43, in <module>
    data = read_mzXML(mzXML_file)
  File "/home/james/Insync/jasm3285@colorado.edu/Google Drive/research/projects/msanalysis/msanalysis/data_extraction/utils.py", line 128, in read_mzXML
    raise ValueError(f"One (or more) empty scans in {filename}, exiting!!")
ValueError: One (or more) empty scans in 20200728_1540.mzXML, exiting!!
```
